"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member,super-init-not-called,unused-argument

import datetime
import typing

import sqlalchemy
from sqlalchemy import orm

from open_alchemy import models

Base = models.Base  # type: ignore


class _CategoryDictBase(typing.TypedDict, total=True):
    """TypedDict for properties that are required."""

    name: str


class CategoryDict(_CategoryDictBase, total=False):
    """TypedDict for properties that are not required."""

    id: int


class TCategory(typing.Protocol):
    """
    SQLAlchemy model protocol.

    Attrs:
        id: Identifikacioni broj (interni ključ)
        name: Naziv kategorije

    """

    # SQLAlchemy properties
    __table__: sqlalchemy.Table
    __tablename__: str
    query: orm.Query

    # Model properties
    id: 'sqlalchemy.Column[int]'
    name: 'sqlalchemy.Column[str]'

    def __init__(self, name: str, id: typing.Optional[int] = None) -> None:
        """
        Construct.

        Args:
            id: Identifikacioni broj (interni ključ)
            name: Naziv kategorije

        """
        ...

    @classmethod
    def from_dict(cls, name: str, id: typing.Optional[int] = None) -> "TCategory":
        """
        Construct from a dictionary (eg. a POST payload).

        Args:
            id: Identifikacioni broj (interni ključ)
            name: Naziv kategorije

        Returns:
            Model instance based on the dictionary.

        """
        ...

    @classmethod
    def from_str(cls, value: str) -> "TCategory":
        """
        Construct from a JSON string (eg. a POST payload).

        Returns:
            Model instance based on the JSON string.

        """
        ...

    def to_dict(self) -> CategoryDict:
        """
        Convert to a dictionary (eg. to send back for a GET request).

        Returns:
            Dictionary based on the model instance.

        """
        ...

    def to_str(self) -> str:
        """
        Convert to a JSON string (eg. to send back for a GET request).

        Returns:
            JSON string based on the model instance.

        """
        ...


Category: typing.Type[TCategory] = models.Category  # type: ignore


class _QuizDictBase(typing.TypedDict, total=True):
    """TypedDict for properties that are required."""

    title: str
    category: str


class QuizDict(_QuizDictBase, total=False):
    """TypedDict for properties that are not required."""

    id: int
    description: typing.Optional[str]
    created_at: typing.Optional[str]


class TQuiz(typing.Protocol):
    """
    SQLAlchemy model protocol.

    Attrs:
        id: Identifikacioni broj (interni ključ)
        title: Naslov kviza
        category: Kategorija kviza
        description: Opis kviza
        created_at: Vreme kreiranja kviza

    """

    # SQLAlchemy properties
    __table__: sqlalchemy.Table
    __tablename__: str
    query: orm.Query

    # Model properties
    id: 'sqlalchemy.Column[int]'
    title: 'sqlalchemy.Column[str]'
    category: 'sqlalchemy.Column[str]'
    description: 'sqlalchemy.Column[typing.Optional[str]]'
    created_at: 'sqlalchemy.Column[typing.Optional[datetime.datetime]]'

    def __init__(self, title: str, category: str, id: typing.Optional[int] = None, description: typing.Optional[str] = None, created_at: typing.Optional[datetime.datetime] = None) -> None:
        """
        Construct.

        Args:
            id: Identifikacioni broj (interni ključ)
            title: Naslov kviza
            category: Kategorija kviza
            description: Opis kviza
            created_at: Vreme kreiranja kviza

        """
        ...

    @classmethod
    def from_dict(cls, title: str, category: str, id: typing.Optional[int] = None, description: typing.Optional[str] = None, created_at: typing.Optional[datetime.datetime] = None) -> "TQuiz":
        """
        Construct from a dictionary (eg. a POST payload).

        Args:
            id: Identifikacioni broj (interni ključ)
            title: Naslov kviza
            category: Kategorija kviza
            description: Opis kviza
            created_at: Vreme kreiranja kviza

        Returns:
            Model instance based on the dictionary.

        """
        ...

    @classmethod
    def from_str(cls, value: str) -> "TQuiz":
        """
        Construct from a JSON string (eg. a POST payload).

        Returns:
            Model instance based on the JSON string.

        """
        ...

    def to_dict(self) -> QuizDict:
        """
        Convert to a dictionary (eg. to send back for a GET request).

        Returns:
            Dictionary based on the model instance.

        """
        ...

    def to_str(self) -> str:
        """
        Convert to a JSON string (eg. to send back for a GET request).

        Returns:
            JSON string based on the model instance.

        """
        ...


Quiz: typing.Type[TQuiz] = models.Quiz  # type: ignore


class _QuestionDictBase(typing.TypedDict, total=True):
    """TypedDict for properties that are required."""

    quiz_id: int
    question_text: str
    option_a: str
    option_b: str
    option_c: str
    option_d: str
    correct_answer: str


class QuestionDict(_QuestionDictBase, total=False):
    """TypedDict for properties that are not required."""

    id: int
    points: int


class TQuestion(typing.Protocol):
    """
    SQLAlchemy model protocol.

    Attrs:
        id: Identifikacioni broj (interni ključ)
        quiz_id: Identifikator kviza kom pitanje pripada
        question_text: Tekst pitanja
        option_a: Ponuđeni odgovor A
        option_b: Ponuđeni odgovor B
        option_c: Ponuđeni odgovor C
        option_d: Ponuđeni odgovor D
        correct_answer: Tačan odgovor (A, B, C ili D)
        points: Broj poena za tačan odgovor

    """

    # SQLAlchemy properties
    __table__: sqlalchemy.Table
    __tablename__: str
    query: orm.Query

    # Model properties
    id: 'sqlalchemy.Column[int]'
    quiz_id: 'sqlalchemy.Column[int]'
    question_text: 'sqlalchemy.Column[str]'
    option_a: 'sqlalchemy.Column[str]'
    option_b: 'sqlalchemy.Column[str]'
    option_c: 'sqlalchemy.Column[str]'
    option_d: 'sqlalchemy.Column[str]'
    correct_answer: 'sqlalchemy.Column[str]'
    points: 'sqlalchemy.Column[int]'

    def __init__(self, quiz_id: int, question_text: str, option_a: str, option_b: str, option_c: str, option_d: str, correct_answer: str, id: typing.Optional[int] = None, points: int = 10) -> None:
        """
        Construct.

        Args:
            id: Identifikacioni broj (interni ključ)
            quiz_id: Identifikator kviza kom pitanje pripada
            question_text: Tekst pitanja
            option_a: Ponuđeni odgovor A
            option_b: Ponuđeni odgovor B
            option_c: Ponuđeni odgovor C
            option_d: Ponuđeni odgovor D
            correct_answer: Tačan odgovor (A, B, C ili D)
            points: Broj poena za tačan odgovor

        """
        ...

    @classmethod
    def from_dict(cls, quiz_id: int, question_text: str, option_a: str, option_b: str, option_c: str, option_d: str, correct_answer: str, id: typing.Optional[int] = None, points: int = 10) -> "TQuestion":
        """
        Construct from a dictionary (eg. a POST payload).

        Args:
            id: Identifikacioni broj (interni ključ)
            quiz_id: Identifikator kviza kom pitanje pripada
            question_text: Tekst pitanja
            option_a: Ponuđeni odgovor A
            option_b: Ponuđeni odgovor B
            option_c: Ponuđeni odgovor C
            option_d: Ponuđeni odgovor D
            correct_answer: Tačan odgovor (A, B, C ili D)
            points: Broj poena za tačan odgovor

        Returns:
            Model instance based on the dictionary.

        """
        ...

    @classmethod
    def from_str(cls, value: str) -> "TQuestion":
        """
        Construct from a JSON string (eg. a POST payload).

        Returns:
            Model instance based on the JSON string.

        """
        ...

    def to_dict(self) -> QuestionDict:
        """
        Convert to a dictionary (eg. to send back for a GET request).

        Returns:
            Dictionary based on the model instance.

        """
        ...

    def to_str(self) -> str:
        """
        Convert to a JSON string (eg. to send back for a GET request).

        Returns:
            JSON string based on the model instance.

        """
        ...


Question: typing.Type[TQuestion] = models.Question  # type: ignore


class _ResultDictBase(typing.TypedDict, total=True):
    """TypedDict for properties that are required."""

    quiz_id: int
    player_name: str
    score: int
    total_questions: int


class ResultDict(_ResultDictBase, total=False):
    """TypedDict for properties that are not required."""

    id: int
    completed_at: typing.Optional[str]


class TResult(typing.Protocol):
    """
    SQLAlchemy model protocol.

    Attrs:
        id: Identifikacioni broj (interni ključ)
        quiz_id: Identifikator kviza za koji je rezultat vezan
        player_name: Ime igrača
        score: Osvojeni bodovi
        total_questions: Ukupan broj pitanja u kvizu
        completed_at: Vreme završetka kviza

    """

    # SQLAlchemy properties
    __table__: sqlalchemy.Table
    __tablename__: str
    query: orm.Query

    # Model properties
    id: 'sqlalchemy.Column[int]'
    quiz_id: 'sqlalchemy.Column[int]'
    player_name: 'sqlalchemy.Column[str]'
    score: 'sqlalchemy.Column[int]'
    total_questions: 'sqlalchemy.Column[int]'
    completed_at: 'sqlalchemy.Column[typing.Optional[datetime.datetime]]'

    def __init__(self, quiz_id: int, player_name: str, score: int, total_questions: int, id: typing.Optional[int] = None, completed_at: typing.Optional[datetime.datetime] = None) -> None:
        """
        Construct.

        Args:
            id: Identifikacioni broj (interni ključ)
            quiz_id: Identifikator kviza za koji je rezultat vezan
            player_name: Ime igrača
            score: Osvojeni bodovi
            total_questions: Ukupan broj pitanja u kvizu
            completed_at: Vreme završetka kviza

        """
        ...

    @classmethod
    def from_dict(cls, quiz_id: int, player_name: str, score: int, total_questions: int, id: typing.Optional[int] = None, completed_at: typing.Optional[datetime.datetime] = None) -> "TResult":
        """
        Construct from a dictionary (eg. a POST payload).

        Args:
            id: Identifikacioni broj (interni ključ)
            quiz_id: Identifikator kviza za koji je rezultat vezan
            player_name: Ime igrača
            score: Osvojeni bodovi
            total_questions: Ukupan broj pitanja u kvizu
            completed_at: Vreme završetka kviza

        Returns:
            Model instance based on the dictionary.

        """
        ...

    @classmethod
    def from_str(cls, value: str) -> "TResult":
        """
        Construct from a JSON string (eg. a POST payload).

        Returns:
            Model instance based on the JSON string.

        """
        ...

    def to_dict(self) -> ResultDict:
        """
        Convert to a dictionary (eg. to send back for a GET request).

        Returns:
            Dictionary based on the model instance.

        """
        ...

    def to_str(self) -> str:
        """
        Convert to a JSON string (eg. to send back for a GET request).

        Returns:
            JSON string based on the model instance.

        """
        ...


Result: typing.Type[TResult] = models.Result  # type: ignore
